version: "3"

services:
  backend:
    platform: linux/amd64
    image: frappe/erpnext:v15.10.3
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - erpnext-sites:/home/frappe/frappe-bench/sites:rw
      - erpnext-logs:/home/frappe/frappe-bench/logs:rw
    networks:
      - mariadb-network
      - erpnext-network
      - redis-network

  queue-long:
    image: frappe/erpnext:v15.10.3
    platform: linux/amd64
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - worker
      - --queue
      - long,default,short
    volumes:
      - erpnext-sites:/home/frappe/frappe-bench/sites:rw
      - erpnext-logs:/home/frappe/frappe-bench/logs:rw
    networks:
      - mariadb-network
      - redis-network
      - erpnext-network

  queue-short:
    image: frappe/erpnext:v15.10.3
    platform: linux/amd64
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - worker
      - --queue
      - short,default
    volumes:
      - erpnext-sites:/home/frappe/frappe-bench/sites:rw
      - erpnext-logs:/home/frappe/frappe-bench/logs:rw
    networks:
      - mariadb-network
      - redis-network
      - erpnext-network

  scheduler:
    image: frappe/erpnext:v15.10.3
    platform: linux/amd64
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - schedule
    volumes:
      - erpnext-sites:/home/frappe/frappe-bench/sites:rw
      - erpnext-logs:/home/frappe/frappe-bench/logs:rw
    networks:
      - mariadb-network
      - redis-network
      - erpnext-network

  websocket:
    image: frappe/erpnext:v15.10.3
    platform: linux/amd64
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    volumes:
      - erpnext-sites:/home/frappe/frappe-bench/sites:rw
      - erpnext-logs:/home/frappe/frappe-bench/logs:rw
    ports:
      - "127.0.0.1:9000:9000"
    expose:
      - 9000
    networks:
      - mariadb-network
      - erpnext-network
      - redis-network

networks:
  mariadb-network:
    name: mariadb-network
    external: true
  redis-network:
    name: redis-network
    external: true
  erpnext-network:
    name: erpnext-network
    external: false

volumes:
  erpnext-db:
    external: true
  erpnext-redis-queue:
    external: true
  erpnext-redis-cache:
    external: true
  erpnext-logs:
    external: true
  erpnext-sites:
    external: true
