version: "3"

services:

  frontend:
    image: frappe/erpnext:v15.10.3
    platform: linux/amd64
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - nginx-entrypoint.sh
    environment:
      BACKEND: backend:8000
      FRAPPE_SITE_NAME_HEADER: frontend
      SOCKETIO: websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
      PROXY_READ_TIMEOUT: 120
      CLIENT_MAX_BODY_SIZE: 50m
    ports:
      - "8080:8080"
    volumes:
      - erpnext-sites:/home/frappe/frappe-bench/sites:rw
      - erpnext-logs:/home/frappe/frappe-bench/logs:rw
    networks:
      - erpnext-network

networks:
  erpnext-network:
    name: erpnext-network
    external: true

volumes:
  erpnext-logs:
    external: true
  erpnext-sites:
    external: true
