services:
  frontend:
    labels:
      # ${ROUTER}-http to use the middleware to redirect to https
      - traefik.http.routers.erpnext-http.middlewares=https-redirect
      # ${ROUTER}-https the actual router using HTTPS
      # Uses the environment variable SITES
      - traefik.http.routers.erpnext-https.rule=Host(`localhost`)
      - traefik.http.routers.erpnext-https.entrypoints=https
      - traefik.http.routers.erpnext-https.tls=true
      # Use the service ${ROUTER} with the frontend
      - traefik.http.routers.erpnext-https.service=erpnext
      # Use the "le" (Let's Encrypt) resolver created below
      - traefik.http.routers.erpnext-https.tls.certresolver=le
